/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\cup.glb -t 
*/

import * as THREE from 'three'
import { useEffect, useRef, type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { useCupMaterial, useCupTexture, useCupTransform } from './CupStore'

export function Cup(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/cup.glb')
  const meshGroup = useRef(new THREE.Group())
  const cupTexture = useCupTexture();
  const cupTransform = useCupTransform();
  const cupMaterial = useCupMaterial();
  const texture = useCupTexture((state) => state.texture);
  const materialRef = useRef<THREE.MeshPhysicalMaterial>(null);

  useEffect(() => {
    if (materialRef.current) {
      materialRef.current.needsUpdate = true;
    }
    useCupTexture.subscribe((state) => {
      // set Scale
      if (texture && texture.repeat.x !== state.textureScale) {
        // Avoid divide-by-zero
        const safeScale = 1 / Math.max(state.textureScale, 0.01);
        texture.repeat.set(safeScale, safeScale);
      }
      // set Position
      if (texture && (texture.offset.x !== state.texturePosX || texture.offset.y !== state.texturePosY)) {
        texture.offset.set(state.texturePosX, state.texturePosY);
      }
      // // set Repeat
      // if (texture && (state.textureRepeat !== prevState.textureRepeat)) {
      //   texture.wrapS = texture.wrapT = state.textureRepeat ? THREE.RepeatWrapping : THREE.ClampToEdgeWrapping;
      //   texture.needsUpdate = true;
      // }
    })
  }, [texture]);

  return (
    <group 
      {...props} 
      ref={meshGroup} 
      dispose={null} 
      scale={cupTransform.scale} 
      rotation={
        [
          cupTransform.rotationX * Math.PI,
          cupTransform.rotationY * Math.PI, 
          cupTransform.rotationZ * Math.PI
        ]}>
      <mesh geometry={(nodes.cup as THREE.Mesh).geometry}>
        <meshPhysicalMaterial
          color={cupMaterial.color}
          roughness={cupMaterial.roughness}
          metalness={cupMaterial.metallic}
          side={THREE.DoubleSide}
          transmission={cupMaterial.transmission}></meshPhysicalMaterial>
      </mesh>
      <mesh geometry={(nodes.cup_body as THREE.Mesh).geometry}>
        <meshPhysicalMaterial
          color={cupMaterial.color}
          roughness={cupMaterial.roughness}
          metalness={cupMaterial.metallic}
          side={THREE.DoubleSide}
          transmission={cupMaterial.transmission}></meshPhysicalMaterial>
      </mesh>
      {
        texture !== null &&
        <mesh geometry={(nodes.cup_image as THREE.Mesh).geometry}>
          <meshPhysicalMaterial
            ref={materialRef}
            map={texture}
            transparent={true}
            roughness={cupTexture.textureRoughness}
            metalness={cupTexture.textureMetalness}
            side={THREE.DoubleSide}
            transmission={cupTexture.textureTransmission}></meshPhysicalMaterial>
        </mesh>
      }
    </group>
  )
}

useGLTF.preload('/cup.glb')
