/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\cup.glb -t 
*/

import * as THREE from 'three'
import { useRef, type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import useCupStore from './CupStore'

export function Cup(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/cup.glb')
  const meshGroup = useRef(new THREE.Group())
  const cupStore = useCupStore();

  // useFrame(() => {
  //   if (cup.AutoRotate) {
  //     const multiplier = cup.Clockwise ? -1 : 1;
  //     meshGroup.current.rotation.y += (0.01 * multiplier);
  //   }
  // })

  return (
    <group {...props} ref={meshGroup} dispose={null} scale={cupStore.scale} rotation={[cupStore.rotationX, cupStore.rotationY, cupStore.rotationZ]}>
      <mesh geometry={(nodes.cup as THREE.Mesh).geometry}>
        <meshPhysicalMaterial
          color={cupStore.color}
          roughness={cupStore.roughness}
          metalness={cupStore.metallic}
          transmission={cupStore.transmission}
          ior={1.2}></meshPhysicalMaterial>
      </mesh>
    </group>
  )
}

useGLTF.preload('/cup.glb')
