/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\shirt.glb -t 
*/

import * as THREE from "three";
import { useEffect, useRef, type JSX } from "react";
import { Edges, Outlines, Select, useGLTF } from "@react-three/drei";
import {
  useBackMaterial,
  useBackTexture,
  useCollarMaterial,
  useFrontMaterial,
  useFrontTexture,
  useLeftSleeveMaterial,
  useLeftSleeveTexture,
  useRightSleeveMaterial,
  useRightSleeveTexture,
  useSelection,
  useShirtTransform,
} from "./ShirtStore";
import { updateTexture } from "../../shared/services/TextureService";
import { inputConstants } from "../../shared/Constants";
import { useTabState } from "../../components/Editor/Properties/PropertiesStore";

export default function Shirt(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/shirt.glb");
  const shirtSelection = useSelection();
  const shirtTransform = useShirtTransform();
  const collarMaterial = useCollarMaterial();
  const frontMaterial = useFrontMaterial();
  const backMaterial = useBackMaterial();
  const rightSleeveMaterial = useRightSleeveMaterial();
  const leftSleeveMaterial = useLeftSleeveMaterial();

  const frontTexture = useFrontTexture((state) => state.texture);
  const frontTextureState = useFrontTexture();
  const frontMaterialRef = useRef<THREE.MeshPhysicalMaterial>(null);

  const backTexture = useBackTexture((state) => state.texture);
  const backTextureState = useBackTexture();
  const backMaterialRef = useRef<THREE.MeshPhysicalMaterial>(null);

  const rightSleeveTexture = useRightSleeveTexture((state) => state.texture);
  const rightSleeveTextureState = useRightSleeveTexture();
  const rightSleeveMaterialRef = useRef<THREE.MeshPhysicalMaterial>(null);

  const leftSleeveTexture = useLeftSleeveTexture((state) => state.texture);
  const leftSleeveTextureState = useLeftSleeveTexture();
  const leftSleeveMaterialRef = useRef<THREE.MeshPhysicalMaterial>(null);

  const tabStore = useTabState();
  
  const handleSelection = (value: THREE.Object3D[]) => {
    if (value.length && tabStore.currentTab === "Product") {
      shirtSelection.setSelected(value[0].name);
    }
  };

  useEffect(() => {
    if (frontMaterialRef.current) {
      frontMaterialRef.current.needsUpdate = true;
    }
    if (backMaterialRef.current) {
      backMaterialRef.current.needsUpdate = true;
    }
    if (rightSleeveMaterialRef.current) {
      rightSleeveMaterialRef.current.needsUpdate = true;
    }
    if (leftSleeveMaterialRef.current) {
      leftSleeveMaterialRef.current.needsUpdate = true;
    }

    useFrontTexture.subscribe((state) => {
      updateTexture(frontTexture, state);
    });

    useBackTexture.subscribe((state) => {
      updateTexture(backTexture, state);
    });

    useRightSleeveTexture.subscribe((state) => {
      updateTexture(rightSleeveTexture, state);
    });

    useLeftSleeveTexture.subscribe((state) => {
      updateTexture(leftSleeveTexture, state);
    });
  }, [frontTexture, backTexture, rightSleeveTexture, leftSleeveTexture]);

  return (
    <group
      {...props}
      dispose={null}
      scale={shirtTransform.scale}
      rotation={[
        shirtTransform.rotationX * Math.PI,
        shirtTransform.rotationY * Math.PI,
        shirtTransform.rotationZ * Math.PI,
      ]}
    >
      <Select onChangePointerUp={(value) => handleSelection(value)}>
        <mesh
          name="Collar"
          geometry={(nodes.Male_TshirtMesh as THREE.Mesh).geometry}
        >
          <meshPhysicalMaterial
            roughness={collarMaterial.roughness}
            metalness={collarMaterial.metallic}
            transmission={collarMaterial.transmission}
            color={collarMaterial.color}
            side={THREE.DoubleSide}
          ></meshPhysicalMaterial>
          <Edges
            lineWidth={inputConstants.outlineThickness}
            scale={inputConstants.outlineScale}
            threshold={45}
            visible={shirtSelection.selectedMesh === "Collar"}
            color={inputConstants.outlineColor}>
          </Edges>
          <Outlines
            thickness={inputConstants.outlineThickness}
            visible={shirtSelection.selectedMesh === "Collar"}
            color={inputConstants.outlineColor}>
          </Outlines>
        </mesh>
        <mesh
          name="Front"
          geometry={(nodes.shirt_front as THREE.Mesh).geometry}
        >
          <meshPhysicalMaterial
            roughness={frontMaterial.roughness}
            metalness={frontMaterial.metallic}
            transmission={frontMaterial.transmission}
            color={frontMaterial.color}
            side={THREE.DoubleSide}
          ></meshPhysicalMaterial>
          <Edges
            lineWidth={inputConstants.outlineThickness}
            scale={inputConstants.outlineScale}
            threshold={45}
            visible={shirtSelection.selectedMesh === "Front"}
            color={inputConstants.outlineColor}>
          </Edges>
          <Outlines
            thickness={inputConstants.outlineThickness}
            visible={shirtSelection.selectedMesh === "Front"}
            color={inputConstants.outlineColor}>
          </Outlines>
        </mesh>
        {frontTexture !== null && (
          <mesh
            name="Front"
            geometry={(nodes.shirt_front_image as THREE.Mesh).geometry}
          >
            <meshPhysicalMaterial
              ref={frontMaterialRef}
              map={frontTexture}
              transparent={true}
              roughness={frontTextureState.textureRoughness}
              metalness={frontTextureState.textureMetalness}
              side={THREE.DoubleSide}
              transmission={frontTextureState.textureTransmission}
            ></meshPhysicalMaterial>
          </mesh>
        )}
        <mesh name="Back" geometry={(nodes.shirt_back as THREE.Mesh).geometry}>
          <meshPhysicalMaterial
            roughness={backMaterial.roughness}
            metalness={backMaterial.metallic}
            transmission={backMaterial.transmission}
            color={backMaterial.color}
            side={THREE.DoubleSide}
          ></meshPhysicalMaterial>
          <Edges
            lineWidth={inputConstants.outlineThickness}
            scale={inputConstants.outlineScale}
            threshold={45}
            visible={shirtSelection.selectedMesh === "Back"}
            color={inputConstants.outlineColor}>
          </Edges>
          <Outlines
            thickness={inputConstants.outlineThickness}
            visible={shirtSelection.selectedMesh === "Back"}
            color={inputConstants.outlineColor}>
          </Outlines>
        </mesh>
        {backTexture !== null && (
          <mesh
            name="Back"
            geometry={(nodes.shirt_back_image as THREE.Mesh).geometry}
          >
            <meshPhysicalMaterial
              ref={backMaterialRef}
              map={backTexture}
              transparent={true}
              roughness={backTextureState.textureRoughness}
              metalness={backTextureState.textureMetalness}
              side={THREE.DoubleSide}
              transmission={backTextureState.textureTransmission}
            ></meshPhysicalMaterial>
          </mesh>
        )}
        <mesh
          name="RightSleeve"
          geometry={(nodes.shirt_right_sleeve as THREE.Mesh).geometry}
        >
          <meshPhysicalMaterial
            roughness={rightSleeveMaterial.roughness}
            metalness={rightSleeveMaterial.metallic}
            transmission={rightSleeveMaterial.transmission}
            color={rightSleeveMaterial.color}
            side={THREE.DoubleSide}
          ></meshPhysicalMaterial>
          <Edges
            lineWidth={inputConstants.outlineThickness}
            scale={inputConstants.outlineScale}
            threshold={90}
            visible={shirtSelection.selectedMesh === "RightSleeve"}
            color={inputConstants.outlineColor}>
          </Edges>
          <Outlines
            thickness={inputConstants.outlineThickness}
            visible={shirtSelection.selectedMesh === "RightSleeve"}
            color={inputConstants.outlineColor}>
          </Outlines>
        </mesh>
        {rightSleeveTexture !== null && (
          <mesh
            name="RightSleeve"
            geometry={(nodes.shirt_right_sleeve_image as THREE.Mesh).geometry}
          >
            <meshPhysicalMaterial
              ref={rightSleeveMaterialRef}
              map={rightSleeveTexture}
              transparent={true}
              roughness={rightSleeveTextureState.textureRoughness}
              metalness={rightSleeveTextureState.textureMetalness}
              side={THREE.DoubleSide}
              transmission={rightSleeveTextureState.textureTransmission}
            ></meshPhysicalMaterial>
          </mesh>
        )}
        <mesh
          name="LeftSleeve"
          geometry={(nodes.shirt_left_sleeve as THREE.Mesh).geometry}
        >
          <meshPhysicalMaterial
            roughness={leftSleeveMaterial.roughness}
            metalness={leftSleeveMaterial.metallic}
            transmission={leftSleeveMaterial.transmission}
            color={leftSleeveMaterial.color}
            side={THREE.DoubleSide}
          ></meshPhysicalMaterial>
          <Edges
            lineWidth={inputConstants.outlineThickness}
            scale={inputConstants.outlineScale}
            threshold={90}
            visible={shirtSelection.selectedMesh === "LeftSleeve"}
            color={inputConstants.outlineColor}>
          </Edges>
          <Outlines
            thickness={inputConstants.outlineThickness}
            visible={shirtSelection.selectedMesh === "LeftSleeve"}
            color={inputConstants.outlineColor}>
          </Outlines>
        </mesh>
        {leftSleeveTexture !== null && (
          <mesh
            name="LeftSleeve"
            geometry={(nodes.shirt_left_sleeve_image as THREE.Mesh).geometry}
          >
            <meshPhysicalMaterial
              ref={leftSleeveMaterialRef}
              map={leftSleeveTexture}
              transparent={true}
              roughness={leftSleeveTextureState.textureRoughness}
              metalness={leftSleeveTextureState.textureMetalness}
              side={THREE.DoubleSide}
              transmission={leftSleeveTextureState.textureTransmission}
            ></meshPhysicalMaterial>
          </mesh>
        )}
      </Select>
    </group>
  );
}

useGLTF.preload("/shirt.glb");
