/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\shirt.glb -t 
*/

import * as THREE from 'three'
import { useEffect, useRef, type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { useBackMaterial, useBackTexture, useCollarMaterial, useFrontMaterial, useFrontTexture, useLeftSleeveMaterial, useLeftSleeveTexture, useRightSleeveMaterial, useRightSleeveTexture, useShirtTransform } from './ShirtStore'

export function Shirt(props: JSX.IntrinsicElements['group']) {
    const { nodes } = useGLTF('/shirt.glb')
    const shirtTransform = useShirtTransform();
    const collarMaterial = useCollarMaterial();
    const frontMaterial = useFrontMaterial();
    const backMaterial = useBackMaterial();
    const rightSleeveMaterial = useRightSleeveMaterial();
    const leftSleeveMaterial = useLeftSleeveMaterial();

    const frontTexture = useFrontTexture((state) => state.texture);
    const frontTextureState = useFrontTexture();
    const frontMaterialRef = useRef<THREE.MeshPhysicalMaterial>(null);

    const backTexture = useBackTexture((state) => state.texture);
    const backTextureState = useBackTexture();
    const backMaterialRef = useRef<THREE.MeshPhysicalMaterial>(null);

    const rightSleeveTexture = useRightSleeveTexture((state) => state.texture);
    const rightSleeveTextureState = useRightSleeveTexture();
    const rightSleeveMaterialRef = useRef<THREE.MeshPhysicalMaterial>(null);

    const leftSleeveTexture = useLeftSleeveTexture((state) => state.texture);
    const leftSleeveTextureState = useLeftSleeveTexture();
    const leftSleeveMaterialRef = useRef<THREE.MeshPhysicalMaterial>(null);

    useEffect(() => {
        if (frontMaterialRef.current) {
            frontMaterialRef.current.needsUpdate = true;
        }
        if (backMaterialRef.current) {
            backMaterialRef.current.needsUpdate = true;
        }
        if (rightSleeveMaterialRef.current) {
            rightSleeveMaterialRef.current.needsUpdate = true;
        }
        if (leftSleeveMaterialRef.current) {
            leftSleeveMaterialRef.current.needsUpdate = true;
        }

        useFrontTexture.subscribe((state) => {
            // set Scale
            if (frontTexture && frontTexture.repeat.x !== state.textureScale) {
                // Avoid divide-by-zero
                const safeScale = 1 / Math.max(state.textureScale, 0.01);
                frontTexture.repeat.set(safeScale, safeScale);
            }
            // set Position
            if (frontTexture && (frontTexture.offset.x !== state.texturePosX || frontTexture.offset.y !== state.texturePosY)) {
                frontTexture.offset.set(state.texturePosX, state.texturePosY);
            }
        })

        useBackTexture.subscribe((state) => {
            // set Scale
            if (backTexture && backTexture.repeat.x !== state.textureScale) {
                // Avoid divide-by-zero
                const safeScale = 1 / Math.max(state.textureScale, 0.01);
                backTexture.repeat.set(safeScale, safeScale);
            }
            // set Position
            if (backTexture && (backTexture.offset.x !== state.texturePosX || backTexture.offset.y !== state.texturePosY)) {
                backTexture.offset.set(state.texturePosX, state.texturePosY);
            }
        })

        useRightSleeveTexture.subscribe((state) => {
            // set Scale
            if (rightSleeveTexture && rightSleeveTexture.repeat.x !== state.textureScale) {
                // Avoid divide-by-zero
                const safeScale = 1 / Math.max(state.textureScale, 0.01);
                rightSleeveTexture.repeat.set(safeScale, safeScale);
            }
            // set Position
            if (rightSleeveTexture && (rightSleeveTexture.offset.x !== state.texturePosX || rightSleeveTexture.offset.y !== state.texturePosY)) {
                rightSleeveTexture.offset.set(state.texturePosX, state.texturePosY);
            }
        })

        useLeftSleeveTexture.subscribe((state) => {
            // set Scale
            if (leftSleeveTexture && leftSleeveTexture.repeat.x !== state.textureScale) {
                // Avoid divide-by-zero
                const safeScale = 1 / Math.max(state.textureScale, 0.01);
                leftSleeveTexture.repeat.set(safeScale, safeScale);
            }
            // set Position
            if (leftSleeveTexture && (leftSleeveTexture.offset.x !== state.texturePosX || leftSleeveTexture.offset.y !== state.texturePosY)) {
                leftSleeveTexture.offset.set(state.texturePosX, state.texturePosY);
            }
        })
    }, [frontTexture, backTexture, rightSleeveTexture, leftSleeveTexture]);

    return (
        <group
            {...props}
            dispose={null}
            scale={shirtTransform.scale}
            rotation={
                [
                    shirtTransform.rotationX * Math.PI,
                    shirtTransform.rotationY * Math.PI,
                    shirtTransform.rotationZ * Math.PI
                ]}>
            <mesh geometry={(nodes.Male_TshirtMesh as THREE.Mesh).geometry}>
                <meshPhysicalMaterial
                    roughness={collarMaterial.roughness}
                    metalness={collarMaterial.metallic}
                    transmission={collarMaterial.transmission}
                    color={collarMaterial.color}
                    side={THREE.DoubleSide}></meshPhysicalMaterial>
            </mesh>
            <mesh geometry={(nodes.shirt_front as THREE.Mesh).geometry}>
                <meshPhysicalMaterial
                    roughness={frontMaterial.roughness}
                    metalness={frontMaterial.metallic}
                    transmission={frontMaterial.transmission}
                    color={frontMaterial.color}
                    side={THREE.DoubleSide}></meshPhysicalMaterial>
            </mesh>
            {
                frontTexture !== null &&
                <mesh geometry={(nodes.shirt_front_image as THREE.Mesh).geometry}>
                    <meshPhysicalMaterial
                        ref={frontMaterialRef}
                        map={frontTexture}
                        transparent={true}
                        roughness={frontTextureState.textureRoughness}
                        metalness={frontTextureState.textureMetalness}
                        side={THREE.DoubleSide}
                        transmission={frontTextureState.textureTransmission}></meshPhysicalMaterial>
                </mesh>
            }
            <mesh geometry={(nodes.shirt_back as THREE.Mesh).geometry}>
                <meshPhysicalMaterial
                    roughness={backMaterial.roughness}
                    metalness={backMaterial.metallic}
                    transmission={backMaterial.transmission}
                    color={backMaterial.color}
                    side={THREE.DoubleSide}></meshPhysicalMaterial>
            </mesh>
            {
                backTexture !== null &&
                <mesh geometry={(nodes.shirt_back_image as THREE.Mesh).geometry}>
                    <meshPhysicalMaterial
                        ref={backMaterialRef}
                        map={backTexture}
                        transparent={true}
                        roughness={backTextureState.textureRoughness}
                        metalness={backTextureState.textureMetalness}
                        side={THREE.DoubleSide}
                        transmission={backTextureState.textureTransmission}></meshPhysicalMaterial>
                </mesh>
            }
            <mesh geometry={(nodes.shirt_right_sleeve as THREE.Mesh).geometry}>
                <meshPhysicalMaterial
                    roughness={rightSleeveMaterial.roughness}
                    metalness={rightSleeveMaterial.metallic}
                    transmission={rightSleeveMaterial.transmission}
                    color={rightSleeveMaterial.color}
                    side={THREE.DoubleSide}></meshPhysicalMaterial>
            </mesh>
            {
                rightSleeveTexture !== null &&
                <mesh geometry={(nodes.shirt_right_sleeve_image as THREE.Mesh).geometry}>
                    <meshPhysicalMaterial
                        ref={rightSleeveMaterialRef}
                        map={rightSleeveTexture}
                        transparent={true}
                        roughness={rightSleeveTextureState.textureRoughness}
                        metalness={rightSleeveTextureState.textureMetalness}
                        side={THREE.DoubleSide}
                        transmission={rightSleeveTextureState.textureTransmission}></meshPhysicalMaterial>
                </mesh>
            }
            <mesh geometry={(nodes.shirt_left_sleeve as THREE.Mesh).geometry}>
                <meshPhysicalMaterial
                    roughness={leftSleeveMaterial.roughness}
                    metalness={leftSleeveMaterial.metallic}
                    transmission={leftSleeveMaterial.transmission}
                    color={leftSleeveMaterial.color}
                    side={THREE.DoubleSide}></meshPhysicalMaterial>
            </mesh>
            {
                leftSleeveTexture !== null &&
                <mesh geometry={(nodes.shirt_left_sleeve_image as THREE.Mesh).geometry}>
                    <meshPhysicalMaterial
                        ref={leftSleeveMaterialRef}
                        map={leftSleeveTexture}
                        transparent={true}
                        roughness={leftSleeveTextureState.textureRoughness}
                        metalness={leftSleeveTextureState.textureMetalness}
                        side={THREE.DoubleSide}
                        transmission={leftSleeveTextureState.textureTransmission}></meshPhysicalMaterial>
                </mesh>
            }
        </group>
    )
}

useGLTF.preload('/shirt.glb')
