/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\soda_can.glb -t 
*/

import * as THREE from 'three'
import { useEffect, useRef, type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import useCanStore from './SodaCanStore'

export function SodaCan(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/soda_can.glb')
  const canStore = useCanStore();
  const texture = useCanStore((state) => state.texture);
  const materialRef = useRef<THREE.MeshPhysicalMaterial>(null);

  useEffect(() => {
    if (materialRef.current) {
      materialRef.current.needsUpdate = true;
    }
    useCanStore.subscribe((state, prevState) => {
      // set Scale
      if (texture && texture.repeat.x !== state.textureScale) {
        // Avoid divide-by-zero
        const safeScale = 1 / Math.max(state.textureScale, 0.01);
        texture.repeat.set(safeScale, safeScale);
      }
      // set Position
      if (texture && (texture.offset.x !== state.texturePosX || texture.offset.y !== state.texturePosY)) {
        texture.offset.set(state.texturePosX, state.texturePosY);
      }
      // set Repeat
      if (texture && (state.textureRepeat !== prevState.textureRepeat)) {
        texture.wrapS = texture.wrapT = state.textureRepeat ? THREE.RepeatWrapping : THREE.ClampToEdgeWrapping;
        texture.needsUpdate = true;
      }
    })
  }, [texture]);

  return (
    <group {...props} dispose={null} scale={canStore.scale} rotation={[canStore.rotationX, canStore.rotationY, canStore.rotationZ]}>
      <mesh geometry={(nodes.Soda_can_metal as THREE.Mesh).geometry}>
        <meshPhysicalMaterial
          color={'#dadada'}
          roughness={0.1}
          side={THREE.DoubleSide}
          metalness={0.9}></meshPhysicalMaterial>
      </mesh>
      <mesh geometry={(nodes.Soda_can_body as THREE.Mesh).geometry}>
        <meshPhysicalMaterial
          color={canStore.color}
          roughness={canStore.roughness}
          metalness={canStore.metallic}
          side={THREE.DoubleSide}
          transmission={canStore.transmission}></meshPhysicalMaterial>
      </mesh>
      {
        texture !== null &&
        <mesh geometry={(nodes.Soda_can_body_image as THREE.Mesh).geometry}>
          <meshPhysicalMaterial
            ref={materialRef}
            map={texture}
            transparent={true}
            roughness={canStore.textureRoughness}
            metalness={canStore.metallic}
            side={THREE.DoubleSide}
            transmission={Math.min(canStore.textureTransmission + 0.1, 1)}></meshPhysicalMaterial>
        </mesh>
      }
    </group>
  )
}

useGLTF.preload('/soda_can.glb')
