/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\soda_can.glb -t 
*/

import * as THREE from "three";
import { useEffect, useRef, type JSX } from "react";
import { Outlines, Select, useGLTF } from "@react-three/drei";
import {
  useCanMaterial,
  useCanTexture,
  useCanTransform,
  useSelection,
} from "./SodaCanStore";
import { updateTexture } from "../../shared/services/TextureService";
import { inputConstants } from "../../shared/Constants";
import { useTabState } from "../../components/Editor/Properties/PropertiesStore";

export default function SodaCan(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/soda_can.glb");
  const canSelection = useSelection();
  const canTexture = useCanTexture();
  const texture = useCanTexture((state) => state.texture);
  const canTransform = useCanTransform();
  const canMaterial = useCanMaterial();
  const materialRef = useRef<THREE.MeshPhysicalMaterial>(null);

  const tabStore = useTabState();

  const handleSelection = (value: THREE.Object3D[]) => {
    if (value.length && tabStore.currentTab === "Product") {
      canSelection.setSelected(value[0].name);
    }
  };

  useEffect(() => {
    if (materialRef.current) {
      materialRef.current.needsUpdate = true;
    }
    useCanTexture.subscribe((state) => {
      updateTexture(texture, state);
    });
  }, [texture]);

  return (
    <group
      {...props}
      dispose={null}
      scale={canTransform.scale}
      rotation={[
        canTransform.rotationX * Math.PI,
        canTransform.rotationY * Math.PI,
        canTransform.rotationZ * Math.PI,
      ]}
    >
      <Select onChangePointerUp={(value) => handleSelection(value)}>
        <mesh geometry={(nodes.Soda_can_metal as THREE.Mesh).geometry}>
          <meshPhysicalMaterial
            color={"#dadada"}
            roughness={0.1}
            side={THREE.DoubleSide}
            metalness={0.9}
          ></meshPhysicalMaterial>
        </mesh>
        <mesh
          name="Can"
          geometry={(nodes.Soda_can_body as THREE.Mesh).geometry}
        >
          <meshPhysicalMaterial
            color={canMaterial.color}
            roughness={canMaterial.roughness}
            metalness={canMaterial.metallic}
            side={THREE.DoubleSide}
            transmission={canMaterial.transmission}
          ></meshPhysicalMaterial>
          <Outlines
            visible={canSelection.selectedMesh === "Can"}
            thickness={inputConstants.outlineThickness}
            color={inputConstants.outlineColor}
          />
        </mesh>
        {texture !== null && (
          <mesh
            name="Can"
            geometry={(nodes.Soda_can_body_image as THREE.Mesh).geometry}
          >
            <meshPhysicalMaterial
              ref={materialRef}
              map={texture}
              transparent={true}
              roughness={canTexture.textureRoughness}
              metalness={canTexture.textureMetalness}
              side={THREE.DoubleSide}
              transmission={canTexture.textureTransmission}
            ></meshPhysicalMaterial>
          </mesh>
        )}
      </Select>
    </group>
  );
}

useGLTF.preload("/soda_can.glb");
