/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\soda_can.glb -t 
*/

import * as THREE from 'three'
import { useEffect, useRef, type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { useCanMaterial, useCanTexture, useCanTransform } from './SodaCanStore';

export default function SodaCan(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/soda_can.glb')
  const canTexture = useCanTexture();
  const texture = useCanTexture((state) => state.texture);
  const canTransform = useCanTransform();
  const canMaterial = useCanMaterial();
  const materialRef = useRef<THREE.MeshPhysicalMaterial>(null);

  useEffect(() => {
    if (materialRef.current) {
      materialRef.current.needsUpdate = true;
    }
    useCanTexture.subscribe((state) => {
      // set Scale
      if (texture && texture.repeat.x !== state.textureScale) {
        // Avoid divide-by-zero
        const safeScale = 1 / Math.max(state.textureScale, 0.01);
        texture.repeat.set(safeScale, safeScale);
      }
      // set Position
      if (texture && (texture.offset.x !== state.texturePosX || texture.offset.y !== state.texturePosY)) {
        const safeScale = 1 / Math.max(state.textureScale, 0.01);
        texture.offset.set(state.texturePosX * safeScale, state.texturePosY * safeScale);
      }
    })
  }, [texture]);

  return (
    <group 
      {...props} 
      dispose={null} 
      scale={canTransform.scale} 
      rotation={
        [
          canTransform.rotationX * Math.PI, 
          canTransform.rotationY * Math.PI, 
          canTransform.rotationZ * Math.PI
        ]}>
      <mesh geometry={(nodes.Soda_can_metal as THREE.Mesh).geometry}>
        <meshPhysicalMaterial
          color={'#dadada'}
          roughness={0.1}
          side={THREE.DoubleSide}
          metalness={0.9}></meshPhysicalMaterial>
      </mesh>
      <mesh geometry={(nodes.Soda_can_body as THREE.Mesh).geometry}>
        <meshPhysicalMaterial
          color={canMaterial.color}
          roughness={canMaterial.roughness}
          metalness={canMaterial.metallic}
          side={THREE.DoubleSide}
          transmission={canMaterial.transmission}></meshPhysicalMaterial>
      </mesh>
      {
        texture !== null &&
        <mesh geometry={(nodes.Soda_can_body_image as THREE.Mesh).geometry}>
          <meshPhysicalMaterial
            ref={materialRef}
            map={texture}
            transparent={true}
            roughness={canTexture.textureRoughness}
            metalness={canTexture.textureMetalness}
            side={THREE.DoubleSide}
            transmission={canTexture.textureTransmission}></meshPhysicalMaterial>
        </mesh>
      }
    </group>
  )
}

useGLTF.preload('/soda_can.glb')
