/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\cup.glb -t 
*/

import * as THREE from 'three'
import { useMemo, type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { useControls } from 'leva'


export function Cup(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/cup.glb')
  const cupOptions = useMemo(() => {
    return {
      Scale: { value: 1.5, min: 1, max: 25, step: 0.2 },
      Color: { value: '#fafafa' },
      Roughness: { value: 0.2, min: 0, max: 1, step: 0.1 },
      Transmission: { value: 0, min: 0, max: 1, step: 0.1 }
    }
  }, [])
  const cup = useControls('Cup', cupOptions)

  return (
    <group {...props} dispose={null} scale={cup.Scale}>
      <mesh geometry={(nodes.cup as THREE.Mesh).geometry}>
        <meshPhysicalMaterial
          color={cup.Color}
          roughness={cup.Roughness}
          transmission={cup.Transmission}
          ior={1.2}></meshPhysicalMaterial>
      </mesh>
    </group>
  )
}

useGLTF.preload('/cup.glb')
