/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\soda_can.glb -t 
*/

import * as THREE from 'three'
import { useMemo, type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { folder, useControls } from 'leva'

export function SodaCan(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/soda_can.glb')
  const canOptions = useMemo(() => {
    return {
      Rotation: folder({
        X: { value: 0, min: 0, max: Math.PI * 2, step: 0.1 },
        Y: { value: 0, min: 0, max: Math.PI * 2, step: 0.1 },
        Z: { value: 0, min: 0, max: Math.PI * 2, step: 0.1 }
      }, { collapsed: true }),
      Scale: { value: 1.5, min: 1, max: 25, step: 0.2 },
    }
  }, [])
  const bodyOptions = useMemo(() => {
    return {
      Color: { value: '#fafafa' },
      Roughness: { value: 0.3, min: 0, max: 1, step: 0.1 },
      Metalness: { value: 0.3, min: 0, max: 1, step: 0.1 },
      Transmission: { value: 0, min: 0, max: 1, step: 0.1 }
    }
  }, [])
  const can = useControls('Soda can', canOptions)
  const body = useControls('Can body', bodyOptions)

  return (
    <group {...props} dispose={null} scale={can.Scale} rotation={[can.X, can.Y, can.Z]}>
      <mesh geometry={(nodes.Soda_can_metal as THREE.Mesh).geometry} material={materials['Can metal material']}>
        <meshPhysicalMaterial
          color={'#eaeaea'}
          roughness={0.1}
          metalness={0.9}></meshPhysicalMaterial>
      </mesh>
      <mesh geometry={(nodes.Soda_can_body as THREE.Mesh).geometry} material={materials['Can metal material']}>
        <meshPhysicalMaterial
          color={body.Color}
          roughness={body.Roughness}
          metalness={body.Metalness}
          transmission={body.Transmission}></meshPhysicalMaterial>
      </mesh>
    </group>
  )
}

useGLTF.preload('/soda_can.glb')
