/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\soda_can_landing_page.glb -t 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { JSX } from 'react'

export function SodaCanLandingPage(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/soda_can_landing_page.glb')
  return (
    <group {...props} dispose={null} rotation={[0, Math.PI/4, 0]} scale={1.2}>
      <mesh receiveShadow castShadow geometry={(nodes.Soda_can_body as THREE.Mesh).geometry} material={materials.white_shd} />
      <mesh receiveShadow castShadow geometry={(nodes.Soda_can_metal as THREE.Mesh).geometry}>
        <meshPhysicalMaterial
          color={'#cacaca'}
          roughness={0.1}
          side={THREE.DoubleSide}
          metalness={1}></meshPhysicalMaterial>
      </mesh>
    </group>
  )
}

useGLTF.preload('/soda_can_landing_page.glb')
