/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\water_bottle.glb -t 
*/

import * as THREE from 'three'
import { useMemo, type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { folder, useControls } from 'leva'

export function WaterBottle(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/water_bottle.glb')
  const bottleOptions = useMemo(() => {
    return {
      Scale: { value: 2.5, min: 1, max: 25, step: 0.2 },
      Bottle: folder({
        'Bottle color': { value: '#fafafa' },
        'Bottle roughness': { value: 0.3, min: 0, max: 1, step: 0.1 },
        'Bottle transmission': { value: 0, min: 0, max: 1, step: 0.1 }
      }, {
        collapsed: true,
      }),
      Cap: folder({
        'Cap color': { value: '#fafafa' },
        'Cap roughness': { value: 0.3, min: 0, max: 1, step: 0.1 },
        'Cap transmission': { value: 0, min: 0, max: 1, step: 0.1 }
      }, {
        collapsed: true,
      }),
    }
  }, [])
  const bottle = useControls('Water bottle', bottleOptions)

  return (
    <group {...props} dispose={null} scale={bottle.Scale}>
      <mesh geometry={(nodes.Bottle as THREE.Mesh).geometry}>
        <meshPhysicalMaterial
          color={bottle['Bottle color']}
          roughness={bottle['Bottle roughness']}
          transmission={bottle['Bottle transmission']}></meshPhysicalMaterial>
      </mesh>
      <mesh geometry={(nodes.Bottle_cap as THREE.Mesh).geometry}>
        <meshPhysicalMaterial
          color={bottle['Cap color']}
          roughness={bottle['Cap roughness']}
          transmission={bottle['Cap transmission']}></meshPhysicalMaterial>
      </mesh>
    </group>
  )
}

useGLTF.preload('/water_bottle.glb')
