/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\water_bottle.glb -t 
*/

import * as THREE from "three";
import { useEffect, useRef, type JSX } from "react";
import { Outlines, Select, useGLTF } from "@react-three/drei";
import {
  useBodyMaterial,
  useBodyTexture,
  useBottleTransform,
  useCapMaterial,
  useSelection,
} from "./WaterBottleStore";
import { updateTexture } from "../../shared/services/TextureService";
import { inputConstants } from "../../shared/Constants";
import { useTabState } from "../../components/Editor/Properties/PropertiesStore";

export default function WaterBottle(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/water_bottle.glb");
  const texture = useBodyTexture((state) => state.texture);
  const bottleSelection = useSelection();
  const bottleTransform = useBottleTransform();
  const capMaterial = useCapMaterial();
  const bodyMaterial = useBodyMaterial();
  const bodyTexture = useBodyTexture();
  const materialRef = useRef<THREE.MeshPhysicalMaterial>(null);
  const tabStore = useTabState();

  const handleSelection = (value: THREE.Object3D[]) => {
    if (value.length && tabStore.currentTab === "Product") {
      bottleSelection.setSelected(value[0].name);
    }
  };

  useEffect(() => {
    if (materialRef.current) {
      materialRef.current.needsUpdate = true;
    }
    useBodyTexture.subscribe((state) => {
      updateTexture(texture, state);
    });
  }, [texture]);

  return (
    <group
      {...props}
      dispose={null}
      scale={bottleTransform.scale}
      rotation={[
        bottleTransform.rotationX * Math.PI,
        bottleTransform.rotationY * Math.PI,
        bottleTransform.rotationZ * Math.PI,
      ]}
    >
      <Select onChangePointerUp={(value) => handleSelection(value)}>
        <mesh name="Cap" geometry={(nodes.Bottle_cap as THREE.Mesh).geometry}>
          <meshPhysicalMaterial
            color={capMaterial.color}
            roughness={capMaterial.roughness}
            metalness={capMaterial.metallic}
            side={THREE.DoubleSide}
            transmission={capMaterial.transmission}
          ></meshPhysicalMaterial>
          <Outlines visible={bottleSelection.selectedMesh==='Cap'} thickness={inputConstants.outlineThickness} color={inputConstants.outlineColor} />
        </mesh>
        <mesh
          name="Bottle"
          geometry={(nodes.Bottle as THREE.Mesh).geometry}
          frustumCulled={false}
        >
          <meshPhysicalMaterial
            color={bodyMaterial.color}
            roughness={bodyMaterial.roughness}
            metalness={bodyMaterial.metallic}
            side={THREE.DoubleSide}
            transmission={bodyMaterial.transmission}
          ></meshPhysicalMaterial>
        </mesh>
        <mesh
          name="Bottle"
          geometry={(nodes.Bottle_body as THREE.Mesh).geometry}
          frustumCulled={false}
        >
          <meshPhysicalMaterial
            color={bodyMaterial.color}
            roughness={bodyMaterial.roughness}
            metalness={bodyMaterial.metallic}
            side={THREE.DoubleSide}
            transmission={bodyMaterial.transmission}
          ></meshPhysicalMaterial>
          <Outlines visible={bottleSelection.selectedMesh==='Bottle'} thickness={inputConstants.outlineThickness} color={inputConstants.outlineColor} />
        </mesh>
        {texture !== null && (
          <mesh
            name="Bottle"
            geometry={(nodes.Bottle_body_image as THREE.Mesh).geometry}
          >
            <meshPhysicalMaterial
              ref={materialRef}
              map={texture}
              transparent={true}
              roughness={bodyTexture.textureRoughness}
              metalness={bodyTexture.textureMetalness}
              side={THREE.DoubleSide}
              transmission={bodyTexture.textureTransmission}
            ></meshPhysicalMaterial>
          </mesh>
        )}
      </Select>
    </group>
  );
}

useGLTF.preload("/water_bottle.glb");
