/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\water_bottle.glb -t 
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import useBottleStore from './WaterBottleStore'

export function WaterBottle(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/water_bottle.glb')
  const bottleStore = useBottleStore();

  return (
    <group {...props} dispose={null} scale={bottleStore.scale} rotation={[bottleStore.rotationX, bottleStore.rotationY, bottleStore.rotationZ]}>
      <mesh geometry={(nodes.Bottle as THREE.Mesh).geometry}>
        <meshPhysicalMaterial
          color={bottleStore.bodyColor}
          roughness={bottleStore.bodyRoughness}
          metalness={bottleStore.bodyMetallic}
          transmission={bottleStore.bodyTransmission}></meshPhysicalMaterial>
      </mesh>
      <mesh geometry={(nodes.Bottle_cap as THREE.Mesh).geometry}>
        <meshPhysicalMaterial
          color={bottleStore.capColor}
          roughness={bottleStore.capRoughness}
          metalness={bottleStore.capMetallic}
          transmission={bottleStore.capTransmission}></meshPhysicalMaterial>
      </mesh>
    </group>
  )
}

useGLTF.preload('/water_bottle.glb')
